### ISSUE TITLE
openssl shouldn't be required

### ISSUE THREAD

**Issue by tko** [messense/robotparser-rs#9]
I'm trying to cross-compile a small web crawler for ARM and the requirement for openssl is making the build fail because I don't have the ARM libraries readily available (nor would I ssl.) While I can depend on hyper with `default-features = false` to avoid openssl the same doesn't seem to be possible with robotparser that drags in openssl (via hyper.)

(Furthermore as I'm caching the http responses and calling the `parse` method so the whole http support is unused, and yet breaking the build.)

**Comment by messense** [comment]
Thank you for bringing it up.
